### ISSUE TITLE
Python functions fail to build with mono repo structure / nested folders

### ISSUE THREAD

**Issue by cmanou** [anomalyco/sst#4114]
It seems as though when you have a python function defined as follows

```
    new sst.aws.Function("MyPythonFunction", {
      handler: "projects/function-a/src/logic.handler",
      runtime: "python3.11",
      url: true,
    });
  ```
  
  You'll hit the following error during the build
  
```
|  Error: Failed to build function "projects/function-a/src/logic.handler": Error: ENOENT: no such file or directory, copyfile '/Users/chris/test-project/projects/function-a/pyproject.toml' -> '/Users/chris/test-project/.sst/artifacts/MyPythonFunction-src/Users/chris/test-project/projects/function-a/pyproject.toml'
|      at file:///Users/chris/test-project/.sst/platform/src/components/aws/function.ts:1378:23 {
|    promise: Promise { <rejected> [Circular *1] }
|  }
```

Guessing this needs to trim the target path to be of the same parent as the project file
https://github.com/sst/ion/blob/5b183e67ed7b9134cd05577b2d417fc7d482534b/platform/src/runtime/python.ts#L73C1-L76C7

**Comment by nyacg** [comment]
I also faced this issue today with v3.2.55 using python container runtime

**Comment by andycloke** [comment]
Same issue with python runtime (non container)

**Comment by andycloke** [comment]
> For zip deployments, one could do something ugly like this temporarily:
> 
>   async run() {
>     const functionA = new sst.aws.Function("FunctionA", {
>       python: {
>         container: false,
>       },
>       handler: "packages/functions/function_a/lambda.handler",
>       runtime: "python3.11",
>       url: true,
>       copyFiles: [{ from: "packages/functions/function_a/lambda.py", to: "packages/functions/function_a/lambda.py" }]
>     });
> 
> Which does allow allow the handler to run with its dependencies. But would break resource linking.

this worked for me to get the lambda function to run, but importing any packages failed

**Comment by aLjTap** [comment]
### Python Function:
```js
export const lambdaAI = new sst.aws.Function("LambdaAI", {
  handler: "src/module/api.handler",
  runtime: "python3.11",
  url: true,
});
```
### Project Tree(as in the simple example)

```
.
|--- module
|    |--- __init__.py
|    |--- api.py
|
|--- pyproject.toml
|--- uv.lock
|--- sst.pypi
```
### .toml:

```toml
[project]
name = "module"
version = "0.1.0"
description = "Lambda function handlers"
dependencies = ["sst", "fastapi==0.115.8", "mangum==0.19.0"]
requires-python = "==3.11.*"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/module"]

[tool.uv.sources]
sst = { git = "https://github.com/sst/sst.git", branch = "dev", subdirectory = "sdk/python" }`

```
### I got this error when I run this project

```bash
|  Error       src/module/api.handler
|  No module named 'api'
|  ↳ Traceback (most recent call last):
|  ↳ File "/Users/user/DEV/root/.sst/artifacts/LambdaAI-dev/lambdaric_python_bridge.py", line 50, in <module>
|  ↳ module = importlib.import_module(module_name)
|  ↳ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|  ↳ File "/Users/user/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/importlib/__init__.py", line 126, in i
mport_module
|  ↳ return _bootstrap._gcd_import(name[level:], package, level)
|  ↳ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|  ↳ File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
|  ↳ File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
|  ↳ File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
|  ↳

````
### this worked, used this ugly method and the error was solved

```js
export const lambdaAI = new sst.aws.Function("LambdaAI", {
  handler: "src/module/api.handler",
  runtime: "python3.11",
  url: true,
  copyFiles: [
    {
      from: "src/module/api.py",
      to: "src/module/api.py",
    },
  ],
});

```
