### ISSUE TITLE
Python Function: UV can't build with SST dependency due to Git failure

### ISSUE THREAD

**Issue by madisonbullard** [anomalyco/sst#5088]
I'm having trouble executing a Python lambda in sst dev. I'm getting an error from uv when I try to call the function: 
```
|  Build       packages/image-analysis/src/function.handler
|  +2562047h     × Invalid `--with` requirement
|  +2562047h     ╰─▶ Git operation failed
```

The error stems from trying to install SST as a dependency via `pyproject.toml`. If I remove the dependency, it builds without error.

I'm following the aws-python example from this repo, and including this in my `pyproject.toml`:
```toml
[tool.uv.sources]
sst = { git = "https://github.com/sst/sst.git", subdirectory = "sdk/python", branch = "dev" }
```

Seems related to [this](https://github.com/sst/sst/blob/bad21bf409eba1ed308aa2b89e0a8bb473b95e78/pkg/runtime/python/python.go#L321) in the python.go file, maybe?
