### ISSUE TITLE
SST deployment stopped working right out of the blue

### ISSUE THREAD

**Issue by bojidaryovchev** [anomalyco/sst#5336]
Hello, I have this workflow and I haven't touched anything neither in the workflow nor in the sst config

```
name: SST Next.js Development Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      # Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      - name: Deploy (Development)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          AUTH_TRUST_HOST: ${{ secrets.AUTH_TRUST_HOST }}
          AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
          AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
        run: |
          npx sst deploy --stage dev

```

All of a sudden I am getting this

```
Run npx sst deploy --stage dev
It seems that your package manager failed to install the right version of the SST CLI for your platform. You can try manually installing the "sst-linux-x64" package.
Error: Process completed with exit code 1.
```

Any idea why?
