### ISSUE TITLE
GitHub Actions Error: kebab-case bucket name causes linking error with Next.js app

### ISSUE THREAD

**Issue by wakeupinagear** [anomalyco/sst#5337]
EDIT: I've gotten around the error by changing the bucket name from kebab-case to camel case. Leaving this issue open since this feels like undocumented behavior (unless I missed something in the docs)

[Shoutout to this issue for making me try removing kebab-case](https://github.com/sst/sst/issues/4977) - seems like this is a larger issue.

Original Issue: I have a basic Next.js app set up with SST, following the [serverless setup guide](https://sst.dev/docs/start/aws/nextjs#serverless). This works properly locally, both when running `npx sst dev` and `npx sst deploy`, but it consistently fails at the "Collecting page data" stage of the Next.js build when running the deploy command in GitHub Actions. The build is being run through `npx sst deploy`, so the multiplexer should be passing this data in?

`Error: S3_BUCKET is not linked in your sst.config.ts`

Some extra context:

* The bucket is only being referenced in backend-only routes; the error occurs when collecting page data for one of those routes
* Changing the bucket name doesn't fix it
* This error happens on many versions; I'm running 3.5.5, but I also tried it with 3.3.0 and 3.2.0 and it still failed (again, only in Actions)

`sst.config.ts`

```
// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
    app(input) {
        const isProd = input?.stage === 'production';
        const region =
            (process.env.AWS_REGION as $utjil.Input<aws.Region>) ?? 'us-west-2';

        return {
            name: 'my-app',
            removal: isProd ? 'retain' : 'remove',
            protect: ['production'].includes(input?.stage),
            home: 'aws',
            providers: {
                aws: { region },
            },
        };
    },
    async run() {
        const isProd = $app.stage === 'production';

        const bucket = new sst.aws.Bucket('user-project-files', {
            access: 'public',
        });

        new sst.aws.Nextjs('AppName', {
            link: [bucket],
            environment: // ENV variables omitted
        });
    },
});
```

`.github/workflows/deploy.yml`

```
name: Build and Deploy with SST

on:
    push:
        branches: [main]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
                  aws-region: ${{ vars.AWS_REGION }}

            # Cache npm dependencies
            - name: Cache node modules
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            # Cache Next.js build output
            - name: Cache Next.js build
              uses: actions/cache@v4
              with:
                  path: |
                      .next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-

            - name: Install dependencies
              run: npm ci

            - name: Deploy
              env: // ENV vars here
              run: npm run deploy
```
