### ISSUE TITLE
Build freezes on the "Creating an optimized production build" step in GitHub Actions

### ISSUE THREAD

**Issue by v-vorobel** [anomalyco/sst#5397]
Hi,
I'm using SST for the first time, and it looks great. Thanks for the package!

I've faced a strange issue, possibly related to the SST. It would be great if anyone could help me resolve this.

So, the problem is when I try to call the `npx sst deploy --stage dev` command in GitHub Actions, it starts building the app but freezes at the *"Creating an optimized production build"* step. This command works well on local.
Also, I've tried to run `npm run build` and `npx open-next@latest build` in the pipeline to be sure this is not a problem with the build itself. And yes, building without SST works well.

Some additional information:

1) Versions:
- SST version: **3.6.9**
- Next.js version: **15.1.4**
- OpenNext version: **v3.3.0**

2) Workflow file:

```yaml
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - dev

concurrency:
  group: dev
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEV_AWS_ROLE_ARN }}
          role-session-name: frontend-dev
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: SST build and deploy application to AWS
        env:
          ACM_CERTIFICATE_ARN: ${{ vars.DEV_ACM_CERTIFICATE_ARN }}
          NEXT_PUBLIC_API_URL: ${{ vars.DEV_NEXT_PUBLIC_API_URL }}
        run: |
          npm ci
          npx sst unlock --stage dev
          npx sst deploy --stage dev
```

3) SST config:

```ts
// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
  app(input) {
    return {
      name: "platform-frontend",
      removal: input?.stage === "production" ? "retain" : "remove",
      protect: ["production"].includes(input?.stage),
      home: "aws",
    };
  },
  async run() {
    new sst.aws.Nextjs("REDACTED", {
      domain: {
        name: $app?.stage === "production" ? "REDACTED" : `${$app.stage}.REDACTED`,
        dns: false,
        cert: process.env.ACM_CERTIFICATE_ARN,
      },
      environment: {
        NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL || '',
      },
    });
  },
});
```

4) Pipeline logs:

![Image](https://github.com/user-attachments/assets/8022fc6e-d92f-4016-8835-a1fc424b0810)

---

## A small hack on how I made it work

I may assume that the issue is somehow related to the Next.js cache. If it's empty, the pipeline freezes.
So, adding the `npm run build` command right before `npx sls deploy` resolves the issue, but I am sure there should be an easier way.

Thanks,
Vadym
