### ISSUE TITLE
Using SST in CI/CD without a cloud provider, local state only

### ISSUE THREAD

**Issue by baartch** [anomalyco/sst#5420]
I'm working on a project where there is no need for any cloud provider (AWS, Cloudflare). So I'm wondering if I can use SST with the local state only in a CI/CD pipeline.

I am thinking about something like
- pushing the local state file to the Git repository
- in the pipeline run SST with this state file (I assume I have to copy it to `~/.config/sst/state/app/<appname>` before running sst commands)
- commit and push the updated state file back to the repository

Has anyone done this before? Is there anything against it?
Which files exaclty do I need to push to the repo?

Btw, the [documentation](https://sst.dev/docs/reference/config/#home) says (in the box **TIP**), the location of the local state should be printed out when running the command. But that's not the case.
```bash
 > bun sst version
sst 3.6.25
```

Thank you for this awesome tool!

**Comment by pauljasperdev** [comment]
Why would you want to use a IaC tool when there is no infrastructure you need?

**Comment by baartch** [comment]
> Why would you want to use a IaC tool when there is no infrastructure you need?

Of course I manage infrastructure. But in this specific project neither on AWS nor on Cloudflare. I want to manage a Grafana Cloud environment. And it works all pretty well. As long as I run `sst deploy` locally. But now I want it in a deployment pipeline.
Requiring an AWS account only to have a fileshare for the state file is something I try to avoid.

**Comment by jayair** [comment]
Yeah this is something we want to support better. You can set your `home: "local"`. But I think since this is mostly undocumented, post it in #general in our Discord.

**Comment by baartch** [comment]
> Yeah this is something we want to support better. You can set your `home: "local"`. But I think since this is mostly undocumented, post it in #general in our Discord.

Thank you for your answer. I know about ``home: "local"`. My question was just, if my described way is currently the best possible. But that's ok. I'll figure it out.

And I want to mention, that the documentation [here](https://sst.dev/docs/reference/config/#home) is possibly wrong. Shouldn't it say `sst version --verbose` prints out the location of the local state? (In the TIP box)

**Comment by baartch** [comment]
Ok. I made it. For those who are curious. This is how I keep the state of my productive stage in the code repo. In the deployment pipeline, the current state is copied into the SST working dir, then the deployment is executed, and in the end the updated stage is commited back to the repo.

I wrote two bash scripts. The first one copies the state from the repo to the sst working dir. It takes the stage name as an argument. (E.g. `./prepare_sst.sh mystagename`)

```bash
#!/bin/bash

SST_STAGE=$1
printf "SST stage: \033[0;32m${SST_STAGE}\033[0m\n"

bun install --frozen-lockfile
bun sst install
bun sst version --verbose

SST_CONFIG=$(bun sst version --verbose | grep config | awk '{split($0,a," "); print a[2]}')
mkdir -p $SST_CONFIG/state/app/observability
mkdir -p $SST_CONFIG/state/passphrase/observability

cp infra/state/app/$SST_STAGE.json $SST_CONFIG/state/app/observability/.
cp infra/state/passphrase/$SST_STAGE.json $SST_CONFIG/state/passphrase/observability/.

set -v
ls -l $SST_CONFIG/state/app/observability
ls -l $SST_CONFIG/state/passphrase/observability
set +v

if [ ! -f $SST_CONFIG/state/app/observability/$SST_STAGE.json ]; then
    echo "State file not found: $SST_CONFIG/state/app/observability/$SST_STAGE.json"
    exit 1
fi
if [ ! -f $SST_CONFIG/state/passphrase/observability/$SST_STAGE.json ]; then
    echo "Passphrase file not found: $SST_CONFIG/state/passphrase/observability/$SST_STAGE.json"
    exit 1
fi
```

The second one copies the state file back to the repo and creates a commit. Pass the stage name as argument as well.
```bash
#!/bin/bash
# © 2025 cloudxs GmbH. All rights reserved. / commit_local_stage.sh 

SST_STAGE=$1
printf "SST stage: \033[0;32m${SST_STAGE}\033[0m\n"


SST_CONFIG=$(bun sst version --verbose | grep config | awk '{split($0,a," "); print a[2]}')

cp $SST_CONFIG/state/app/observability/$SST_STAGE.json infra/state/app/.
cp $SST_CONFIG/state/passphrase/observability/$SST_STAGE.json infra/state/passphrase/.


git checkout -b main
git add .
git commit -m "feat: Update SST state"
git push --set-upstream origin main
```


And this is the part in my Azure DevOps pipeline
```yaml
  - stage: Deploy
    condition: or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'BatchedCI'))
    jobs:
      - job: deploy
        displayName: Deploy
        steps:
          - checkout: self
            persistCredentials: true

          - script: |
              git config --global user.email 'mail@mydomain.ch' & git config --global user.name 'Deploy Pipeline'
            workingDirectory: $(System.DefaultWorkingDirectory)
            displayName: Set Git Config

          - task: Npm@1
            displayName: install bun
            inputs:
              command: custom
              customCommand: install -g bun

          - task: Cache@2
            displayName: Cache node_modules
            inputs:
              key: 'bun | "$(Agent.OS)" | bun.lockb'
              path: 'node_modules'

          - task: Bash@3
            displayName: Prepare SST
            inputs:
              filePath: infra/state/prepare_sst_stage.sh
              arguments: $(SST_STAGE)

          - bash: |
              bun sst refresh --stage $(SST_STAGE) --print-logs
            displayName: Refresh SST state

          - bash: |
              bun sst deploy --stage $(SST_STAGE) --print-logs
            displayName: Deploy SST

          - task: Bash@3
            displayName: Commit SST state
            inputs:
              filePath: infra/state/commit_local_stage.sh
              arguments: $(SST_STAGE)
```
