### ISSUE TITLE
Add multiple binary support for Rust Lambdas.

### ISSUE THREAD

**Issue by RylanYancey** [anomalyco/sst#5676]
I'd like to set up my Cargo.toml like this, where one project (with a shared library and multiple binaries) can provide multiple lambdas. 
```toml
[lib]
name = "common"
path = "src/lib.rs"

[[bin]]
name = "lambda1"
path = "src/bin/lambda1.rs"

[[bin]]
name = "lambda2"
path = "src/bin/lambda2.rs"
```
Right now, SST looks for a `target/lambda/bootstrap` binary, but when there are multiple binary targets, multiple folders are created. In this case, `target/lambda/lambda1/bootstrap` and `target/lambda/lambda2/bootstrap`. I propose a syntax like this:
```rs
api.route('POST /lambda1', {
    handler: "/packages/crates.lambda1",
    runtime: "rust",
})
```
When the handler path contains a period, it should indicate the specific binary to look for.
