### ISSUE TITLE
Disabling CORS for a `SvelteKit` component

### ISSUE THREAD

**Issue by handlebauer** [anomalyco/sst#5763]
I spent quite a while stumped on why my deployed SvelteKit app was setting the value of `Access-Control-Allow-Origin` to `*` with seemingly no way to disable this or otherwise modify it. I tracked the setting down to the associated Lamda function:

```
Description: An AWS Serverless Application Model template describing your function.
Resources:
    Type: AWS::Serverless::Function
    Properties:
      Description: xxx
      MemorySize: 1024
      Runtime: nodejs20.x
      FunctionUrlConfig:
        ...
        Cors:
          AllowCredentials: false
          AllowOrigins:
            - '*'
          AllowHeaders:
            - '*'
          AllowMethods:
            - '*'
``` 

I don't see any way to change this via SST v3. Am I missing something?
