### ISSUE TITLE
Bug: Python container build fails with "Dockerfile: no such file or directory" in artifacts when custom Dockerfile exists

### ISSUE THREAD

**Issue by mike-baton** [anomalyco/sst#5822]
**Describe the bug**
When attempting to deploy a Python Lambda function using `python: { container: true }` and providing a custom `Dockerfile` in the function's source directory, the `sst deploy` command fails. The error indicates that SST's Docker build process cannot find a `Dockerfile` within its internal artifact staging directory (`.sst/artifacts/<FunctionName>-src/Dockerfile`), even though a custom `Dockerfile` is present in the specified handler/bundle path.

This occurs even when the project structure and `sst.aws.Function` configuration seem to align with the SST documentation for custom Dockerfiles with Python container functions.

**To Reproduce**

1.  Project Structure:
    ```
    notifications-monorepo/
    ├── sst.config.ts
    ├── pyproject.toml  (Root workspace definition)
    ├── functions/
    │   └── datadog-forwarder/
    │       └── logs_monitoring/    <-- Function source root
    │           ├── Dockerfile      <-- Custom Dockerfile
    │           ├── pyproject.toml  <-- Lambda's specific pyproject.toml
    │           ├── requirements.txt
    │           └── lambda_function.py (and other Python source files)
    └── infra/
        └── functions/
            └── datadog-forwarder.ts <-- SST Function definition
    ```

2.  `notifications-monorepo/pyproject.toml` (Root):
    ```toml
    [project]
    name = "notifications-monorepo-workspace"
    version = "0.1.0"
    requires-python = ">=3.12"
    dependencies = []

    [tool.uv.workspace]
    members = [
        "functions/datadog-forwarder/logs_monitoring"
    ]
    ```

3.  `functions/datadog-forwarder/logs_monitoring/pyproject.toml` (Lambda-specific):
    ```toml
    [project]
    name = "datadog-forwarder-lambda"
    version = "0.1.0"
    description = "Datadog Forwarder Lambda"
    requires-python = "==3.12.*" 
    dependencies = [
      "attrs", "bytecode", "cattrs", "certifi", "charset-normalizer",
      "datadog-lambda==6.104.0", "datadog==0.50.2", "ddsketch==3.0.1",
      "ddtrace==2.17.3", "deprecated", "envier", "exceptiongroup", "idna==3.7",
      "importlib-metadata", "opentelemetry-api", "protobuf", "requests-futures",
      "requests", "six", "typing-extensions", "urllib3>=1.26.19,<3.0",
      "wrapt==1.14.0", "xmltodict", "zipp", "ujson"
    ]
    # No [build-system] or [tool.uv.sources]
    ```

4.  `functions/datadog-forwarder/logs_monitoring/Dockerfile` (Custom Dockerfile):
    ```dockerfile
    ARG PYTHON_VERSION=3.12
    FROM public.ecr.aws/lambda/python:${PYTHON_VERSION}

    USER root 
    RUN microdnf update -y && \
        microdnf install -y git gcc findutils && \
        microdnf clean all
    USER ${LAMBDA_UID}

    COPY --from=ghcr.io/astral-sh/uv:0.2.24 /uv /usr/local/bin/uv

    WORKDIR ${LAMBDA_TASK_ROOT}

    COPY pyproject.toml . 
    COPY requirements.txt . 

    RUN /usr/local/bin/uv pip install -r requirements.txt --target ${LAMBDA_TASK_ROOT} --system

    # COPY all necessary application files from Datadog forwarder source
    COPY lambda_function.py .
    COPY __init__.py .
    COPY resource.enc .
    COPY caching/ ./caching/
    COPY customized_log_group.py .
    COPY enhanced_lambda_metrics.py .
    COPY forwarder.py .
    COPY retry/ ./retry/
    COPY settings.py .
    COPY steps/ ./steps/
    COPY telemetry.py .
    COPY trace_forwarder/ ./trace_forwarder/

    CMD [ "lambda_function.lambda_handler" ]
    ```

5.  `infra/functions/datadog-forwarder.ts` (SST `Function` definition):
    ```typescript
    // ... imports ...
    export function DatadogForwarder() {
      const lambda = new sst.aws.Function("DatadogForwarder", {
        handler: "functions/datadog-forwarder/logs_monitoring/lambda_function.lambda_handler", 
        runtime: "python3.12", 
        python: {
          container: true, 
        },
        environment: { /* ... DD_API_KEY, DD_SITE, etc. ... */ },
        link: [ /* ... */ ],
        memory: "512 MB", 
        permissions: [ /* ... */ ],
        timeout: "300 seconds", 
      });
      return { datadogForwarder: lambda };
    }
    ```

6.  Run `bun sst deploy --stage devnet --target DatadogForwarder --verbose` (Docker daemon is running).

**Expected behavior**
SST should detect the custom `Dockerfile` in `functions/datadog-forwarder/logs_monitoring/`, copy it and the associated build context to `.sst/artifacts/DatadogForwarder-src/`, and then successfully build the Docker image using this custom Dockerfile. The deployment should then proceed, and the Lambda should run with its dependencies correctly installed (solving earlier `ImportModuleError` issues).

**Actual behavior**
The deployment fails with the following error:
```
|  Error       DatadogForwarderImage docker-build:index:Image
docker-build:index:Image resource 'DatadogForwarderImage': property dockerfile.location value {<nil>} has a problem: open /Users/mike/dev/work/notifications-monorepo/.sst/artifacts/DatadogForwarder-src/Dockerfile: no such file or directory

✕  Failed

DatadogForwarderImage docker-build:index:Image
docker-build:index:Image resource 'DatadogForwarderImage': property dockerfile.location value {<nil>} has a problem: open /Users/mike/dev/work/notifications-monorepo/.sst/artifacts/DatadogForwarder-src/Dockerfile: no such file or directory
```
This indicates that SST's build process is not finding or placing the `Dockerfile` in the expected artifact staging location (`.sst/artifacts/DatadogForwarder-src/`) before attempting the Docker build.

**Environment :**
*   SST Version: `3.16.0`

**Additional context**
*   This issue was encountered while trying to deploy the standard Datadog Forwarder Lambda function.
*   The goal is to use a custom Dockerfile to ensure correct Python dependency installation, as the default zip-based bundling (even with `pyproject.toml` and `uv` workspace setup) was resulting in `ImportModuleError: No module named 'requests'`.
*   The project uses `uv` workspaces, with a root `pyproject.toml` and a `pyproject.toml` for the Lambda function.
*   The same error ("Dockerfile: no such file or directory" in artifacts) occurs whether using `bundle` property or just `handler` property in `sst.aws.Function` when `python: { container: true }` is set.
*   The issue seems to be that SST's mechanism for copying the custom `Dockerfile` into its build staging area is failing.
