### ISSUE TITLE
[Feature Request] Push secrets without `sst deploy`

### ISSUE THREAD

**Issue by apetta** [anomalyco/sst#5858]
It would be great to be able to push Secrets to AWS without deploying everything else. i.e. something like `sst secret deploy/publish`.

We currently have Github actions handling all the deployments via CI/CD. Without being able to push just the secrets, it makes it quite awkward to add new secrets as we need to sidestep the CI/CD deployment to ensure secrets are made available before the GH actions can deploy safely.

With something like `sst secret deploy/publish`, we can set the secret & publish it from local machine and then let CI/CD do its thing.

**Comment by mike-baton** [comment]
+1 on this

**Comment by jayair** [comment]
For this CI/CD flow is this for PR stages? Would the setting the secret fallback work for that?

**Comment by apetta** [comment]
> For this CI/CD flow is this for PR stages? Would the setting the secret fallback work for that?

Hey, so we have CI/CD on `dev`, `staging`, and `production` stages from dev, staging, and main branches on GH respectively. All local dev happens via `sst dev` on personal stages. We don't use PR stages.

I don't think the fallback would work for us as I'm looking to set secrets for prod, staging & dev. Right now, I have to sidestep CI/CD unfortunately.

**Comment by jayair** [comment]
I'm a little confused then. Can you describe what you are doing currently in steps?

**Comment by apetta** [comment]
> I'm a little confused then. Can you describe what you are doing currently in steps?

Yes, of course!

Development starts locally on `feature/*` branches and is tested using `sst dev` (personal stages). When happy, we merge these branches into `dev` _branch_ - triggering GH action deploy to `dev` _stage_. If all looks ok, we merge `dev` _branch_ to `staging` and then from there to `main` _branch_ - resulting in GH actions that deploy to `staging` and `production` _stages_ respectively. Each of the three stages have distinct secrets for various reasons (e.g. x3 MongoDB Atlas projects).

Ideally, we never want to run `sst deploy` from our local machines - leaving that to the GH actions. When I want to add a new secret (or when running `sst secret load .env.production --stage production` as I had to recently), I have to deploy the full app from my local machine to all stages first and then let CI/CD run as usual. So, it would be great to push out just the secrets from local, and then just re-trigger the GH action or push some code for _actual_ deploy.

If it helps, here's our current GH action for deployment:
```yaml
name: Deploy SST App

on:
  push:
    branches:
      - dev
      - main
      - staging

jobs:
  deploy:
    concurrency:
      group: ${{ github.ref_name }}
      cancel-in-progress: true
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Determine deployment stage
        id: stage
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "stage=dev" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "stage=production" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "stage=staging" >> $GITHUB_OUTPUT
          else
            echo "Branch not recognized for deployment."
            exit 1
          fi
        shell: bash

      - name: Cache SST Build Artifacts
        id: sst-cache
        uses: actions/cache@v3
        with:
          path: ./.sst
          key: ${{ runner.os }}-sst-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-sst-

      - name: Pre-deploy checks
        run: pnpm run ci

      - name: Refresh SST
        if: steps.sst-cache.outputs.cache-hit != 'false'
        run: pnpm sst refresh --stage ${{ steps.stage.outputs.stage }}

      - name: Deploy SST app
        run: pnpm sst deploy --stage ${{ steps.stage.outputs.stage }}

```

As a workaround, I guess I could set these secrets in GH Secrets and inject them in with `sst secret set` in the action, but it would be nice to do it directly from my local machine.

Thanks!!
