### ISSUE TITLE
Authorizer does not get attached to Route

### ISSUE THREAD

**Issue by zzzolcsi** [anomalyco/sst#5937]
I'm trying to link an Authorizer to a Route, but it does not get attached.

```
export default $config({
  app(input) {
    return {
      name: "monorepo-template",
      removal: input?.stage === "production" ? "retain" : "remove",
      protect: ["production"].includes(input?.stage),
      home: "aws",
    };
  },

  async run() {
    const api = new sst.aws.ApiGatewayV2("TestAPI", {});

    const testUserPool = new aws.cognito.UserPool("TestUserPool", {});

    const testUserPoolClient = new aws.cognito.UserPoolClient("TestUserPoolClient", {
      userPoolId: testUserPool.id,
    });

    const region = aws.getRegionOutput().name;
    const testAuthorizer = api.addAuthorizer({
      name: "TestAuthorizer",
      jwt: {
        issuer: $interpolate`https://cognito-idp.${region}.amazonaws.com/${testUserPool.id}`,
        audiences: [testUserPoolClient.id]
      }
    })

    const route = api.route("GET /", {
      handler: "packages/functions/src/api.handler",
      auth: {
        jwt: {
          authorizer: testAuthorizer.id
        }
      },
    });

    return {
      API: api.nodes.api.name,
      Authorizer: testAuthorizer.id,
      UserPool: testUserPool.name,
      UserPoolClient: testUserPoolClient.id,
      Route: route.nodes.route.id,
      RouteAuthorizerId: route.nodes.route.authorizerId,
    };
  },
});
```

```
   Authorizer: btrmzk
   Route: 73qefcd
   RouteAuthorizerId: 
   UserPool: TestUserPool-2b6e4ba
   UserPoolClient: 5v7930gnskvcca68ggvq6audv7
   API: monorepo-template-zoltan-TestAPIApi-xovmtude

```

All resources get created, but the authorizer does not get linked to the route. What am I missing?
sst 3.17.8
